name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Check types
        run: npm run typecheck

      - name: Run the tests
        run: npm run test:coverage

      - name: Build
        run: npm run build

      - name: Test that works on esm-vitest-express
        run: bash test/e2e/esm-vitest-express/run.sh

      - name: Test that works on esm-node-express
        run: bash test/e2e/esm-node-express/run.sh

      - name: Test that works on nestjs
        run: bash test/e2e/nestjs/run.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
